I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/classes.rpy", line 1, in script
    init python:
  File "game/classes.rpy", line 1, in script
    init python:
  File "game/classes.rpy", line 22, in <module>
    class Lists:
  File "game/classes.rpy", line 24, in Lists
    Fact("Likes cats"), [
TypeError: __init__() takes exactly 3 arguments (2 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/sean/Downloads/renpy-7.4.8-sdk/renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "/home/sean/Downloads/renpy-7.4.8-sdk/renpy/main.py", line 515, in main
    renpy.game.context().run(node)
  File "game/classes.rpy", line 1, in script
    init python:
  File "game/classes.rpy", line 1, in script
    init python:
  File "/home/sean/Downloads/renpy-7.4.8-sdk/renpy/ast.py", line 923, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/sean/Downloads/renpy-7.4.8-sdk/renpy/python.py", line 2235, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/classes.rpy", line 22, in <module>
    class Lists:
  File "game/classes.rpy", line 24, in Lists
    Fact("Likes cats"), [
TypeError: __init__() takes exactly 3 arguments (2 given)

Linux-5.4.0-84-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.4.8.1895
GameJam2021 1.0
Sat Sep 18 16:36:51 2021
